Added user input parameters
Inputs added:
- MAINFOLDER
- KMER length
- REFILEO :: added to let user input both files and folders

diff --git a/bin/acomp b/bin/acomp
--- a/bin/acomp
+++ b/bin/acomp
@@ -7,17 +7,41 @@ FORMAT=fasta
 SKIP=0
 REPEAT=0
 MAINFOLDER=.
+REFILEO=.
 COUNT=0
 
+#Default locations
 DIRS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"    #where is the acomp file?
 DIR=$( dirname ${DIRS} ) #go one level up from location of acomp file
 MAINFOLDER=$( echo "${DIR}" | sed -e "s/\/*$//" ) #remove trailing / if necessary
+
+while getopts o:k:i option
+do
+	case "${option}"
+	in
+	o) MAINFOLDER=${OPTARG};;
+	k) KMER=${OPTARG};;
+	i) REFFILEO=${OPTARG};;
+	?/ ) echo "ERROR: Unknown Option" exit 1;;
+	esac
+done
+
+MAINFOLDER=$( echo "${MAINFOLDER}" | sed -e "s/\/*$//" )
 MINIAFOLDER=$( echo "${MAINFOLDER}"/miniaOutput )
 BOWTIEFOLDER=$( echo "${MAINFOLDER}"/bowtieOutput )
 SAMFOLDER=$( echo "${MAINFOLDER}"/samFiles )
 VELVETFOLDER=$( echo "${MAINFOLDER}"/velvetoutput )
 
-REFFILES=( $( find "${MAINFOLDER}" -name "*.${FORMAT}" ) )     #all FORMAT file paths as array
+if [ (("$REFILEO" != ".")) -a (( -d ${REFILEO} )) ]; then
+	REFILEO=$( echo "${REFILEO}" | sed -e "s/\/*$//" )
+	REFFILES=( $( find "${REFILEO}" -name "*.${FORMAT}" ) )     #all FORMAT file paths as array
+elif [ (("$REFILEO" != ".")) && (( -a ${REFILEO} )) ]; then 
+	REFILEO=$( echo "${REFILEO}" | sed -e "s/\/*$//" )
+	REFFILES=( $( find "{REFILEO}" -name "*.${FORMAT}" ) )
+else
+	REFFILES=( $( find "${MAINFOLDER}" -name "*.${FORMAT}" ) )
+fi
+
 #REFFILES=( "${MAINFOLDER}/reads.fasta" ) #Testing REFFILES with pipeline
 #for F in "${REFFILES[@]}"; do echo "${F}"; done
 #for F in "${REFFILES[@]}"; do echo $(basename "${F}"); done
